---
- name: Includes dynamic configuration file
  include_vars: "{{ vars_files }}"
  when: vars_files is defined

- name: mount_network_fs | Install base packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - cifs-utils

- name: mount_network_fs | Umount CIFS share
  mount:
    name: "{{ network_fs_base_directory }}/{{ network_fs_cifs_hostname }}/{{ network_fs_mount_directory }}"
    src: "//{{ network_fs_cifs_hostname }}/{{ network_fs_cifs_directory | regex_replace('^/', '') }}"
    fstype: 'cifs'
    opts: "{{ network_fs_cifs_options }},_netdev"
    state: 'unmounted'
  when: network_fs_mount_type == "cifs" and network_fs_active == false and network_fs_cifs_options is defined

- name: mount_network_fs | Mount CIFS share
  mount:
    name: "{{ network_fs_base_directory }}/{{ network_fs_cifs_hostname }}/{{ network_fs_mount_directory }}"
    src: "//{{ network_fs_cifs_hostname }}/{{ network_fs_cifs_directory | regex_replace('^/', '') }}"
    fstype: 'cifs'
    opts: "{{ network_fs_cifs_options }},_netdev"
    state: 'mounted'
  when: network_fs_mount_type == "cifs" and network_fs_active == true and network_fs_cifs_options is defined

